# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

# pool:
#   vmImage: 'Ubuntu 16.04'

# steps:
# - task: Maven@3
#   inputs:
#     mavenPomFile: '$(system.defaultWorkingDirectory)/tema_2/pom.xml'
#     mavenOptions: '-Xmx3072m'
#     javaHomeOption: 'JDKVersion'
#     jdkVersionOption: '1.8'
#     jdkArchitectureOption: 'x64'
#     publishJUnitResults: true
#     testResultsFiles: '**/TEST-*.xml'
#     goals: 'package'

jobs:
- job: Ubuntu 16.04
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: Maven@3
    inputs:
      mavenPomFile: '$(system.defaultWorkingDirectory)/tema_2/pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      goals: 'package'

- job: macOS 10.13
  pool:
    vmImage: 'xcode9-macos10.13'
  steps:
  - task: Maven@3
    inputs:
      mavenPomFile: '$(system.defaultWorkingDirectory)/tema_2/pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      goals: 'package'

- job: vs2017 win2016
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: Maven@3
    inputs:
      mavenPomFile: '$(system.defaultWorkingDirectory)/tema_2/pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      goals: 'package'